[project]
name = "ultimatevocalremovergui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kasumikira", email = "69134445+kasumikira@users.noreply.github.com" }
]
requires-python = ">=3.10,<3.11"
dependencies = [
    "altgraph==0.17.3",
    "asteroid==0.7.0",
    "audiomentations==0.24.0",
    "audioread==3.0.0",
    "beartype==0.14.1",
    "certifi==2022.12.7",
    "cffi==1.15.1",
    "cryptography==3.4.6",
    "diffq>=0.2.4",
    "einops==0.6.0",
    "future==0.18.3",
    "julius==0.2.7",
    "kthread==0.2.3",
    "librosa==0.9.2",
    "llvmlite>=0.49.0",
    "matchering==2.0.6",
    "ml-collections==0.1.1",
    "natsort==8.2.0",
    "numpy==1.23.5",
    "omegaconf==2.2.3",
    "onnx>=1.17.0",
    "onnx2pytorch>=0.5.3",
    "opencv-python==4.6.0.66",
    "pillow==9.3.0",
    "playsound==1.2.2",
    "protobuf==3.20.3",
    "psutil==5.9.4",
    "pydub==0.25.1",
    "pyglet==1.5.23",
    "pyperclip==1.8.2",
    "pyrubberband==0.3.0",
    "pysoundfile==0.9.0.post1 ; sys_platform == 'darwin'",
    "pytorch-lightning==2.0.0",
    "pyyaml==6.0",
    "resampy==0.4.2",
    "rotary-embedding-torch==0.3.5",
    "ruamel-yaml>=0.19.1",
    "samplerate==0.1.0",
    "scipy>=1.9.3",
    "screeninfo==0.8.1",
    "segmentation-models-pytorch==0.3.3",
    "setuptools==81.0.0",
    "soundfile==0.11.0 ; sys_platform != 'darwin'",
    "soundstretch==1.2",
    # "timm==0.9.2",
    "spafe==0.3.2",
    "torch-audiomentations>=0.12.0",
    "transformers==4.35.0",
    "urllib3==1.26.12",
    "wget==3.2",
]

[project.optional-dependencies]
cpu = [
    "torch==2.11.0+cpu",
    "torchvision==0.26.0+cpu",
    "torchaudio==2.11.0+cpu",
    "onnxruntime==1.23.2",
]
cuda = [
    "torch==2.11.0+cu128",
    "torchvision==0.26.0+cu128",
    "torchaudio==2.11.0+cu128",
    "onnxruntime-gpu==1.23.2",
]
rocm = [
    "torch[device-all]==2.11.0+rocm7.14.1 ; (sys_platform == 'win32' and platform_machine == 'AMD64') or (sys_platform == 'linux' and platform_machine == 'x86_64')",
    "torchvision[device-all]==0.26.0+rocm7.14.1 ; (sys_platform == 'win32' and platform_machine == 'AMD64') or (sys_platform == 'linux' and platform_machine == 'x86_64')",
    "torchaudio==2.11.0+rocm7.14.1 ; (sys_platform == 'win32' and platform_machine == 'AMD64') or (sys_platform == 'linux' and platform_machine == 'x86_64')",
    "onnxruntime==1.23.2",
]

[tool.uv]
package = false
index-strategy = "unsafe-first-match"
override-dependencies = [
    { package = { name = "torch", version = "2.11.0+rocm7.14.1" }, dependencies = ["triton==3.8.0+git4cff872c.rocm7.14.1 ; sys_platform == 'linux'", "amd-torch-device-gfx1250==2.11.0+rocm7.14.1 ; sys_platform == 'linux'", "amd-torch-device-gfx942==2.11.0+rocm7.14.1 ; sys_platform == 'linux'", "amd-torch-device-gfx950==2.11.0+rocm7.14.1 ; sys_platform == 'linux'"] },
    { package = { name = "torchvision", version = "0.26.0+rocm7.14.1" }, dependencies = ["amd-torchvision-device-gfx1250==0.26.0+rocm7.14.1 ; sys_platform == 'linux'", "amd-torchvision-device-gfx942==0.26.0+rocm7.14.1 ; sys_platform == 'linux'", "amd-torchvision-device-gfx950==0.26.0+rocm7.14.1 ; sys_platform == 'linux'"] },
]
conflicts = [
    [
        { extra = "cpu" },
        { extra = "cuda" },
    ],
    [
        { extra = "cpu" },
        { extra = "rocm" },
    ],
    [
        { extra = "cuda" },
        { extra = "rocm" },
    ],
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu128", extra = "cuda" },
    { index = "amd-rocm", extra = "rocm" },
]
torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu128", extra = "cuda" },
    { index = "amd-rocm", extra = "rocm" },
]
torchaudio = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu128", extra = "cuda" },
    { index = "amd-rocm", extra = "rocm" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "amd-rocm"
url = "https://repo.amd.com/rocm/whl-multi-arch/"
explicit = false
ignore-error-codes = [403]

[dependency-groups]
dev = [
    "pyinstaller==6.15.0",
]
